### ISSUE TITLE
Providing unit-tests

### ISSUE THREAD

**Issue by ubcent** [ubcent/react-circular-color#1]

**Comment by paulkotov** [comment]
gonna test it to check if those rendered correctly:
- path ;
- class accepted;
- square is drawn;

**Comment by ubcent** [comment]
Please check the event firing if possible

**Comment by paulkotov** [comment]
Sure

**Comment by ubcent** [comment]
@paulkotov any updates? I just want to note that I've added a new property and we should test it as well. See #4 for more details.
