### ISSUE TITLE
prop to indicate the color value

### ISSUE THREAD

**Issue by paxarpp** [ubcent/react-circular-color#10]
### New Issue Checklist

- [x] Updated package to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/ubcent/react-circular-color/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/ubcent/react-circular-color/issues)

### Issue Description

It would be great if we have a property to indicate the color value. Now the default is selected.

**Comment by ubcent** [comment]
@paxarpp thx for reporting, I'll try to figure out what the problem is asap. Or don't you mind to make a pull request?

**Comment by paxarpp** [comment]
yes, I will be happy to participate

**Comment by ubcent** [comment]
Fixed
