### ISSUE TITLE
Re-write the package using fucntional component and typescript

### ISSUE THREAD

**Issue by walosha** [ubcent/react-circular-color#17]
### New Issue Checklist
  Would you mind if i re-write the package using fucntional component and typescript.

Thanks
- [x] Updated package to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/ubcent/react-circular-color/blob/master/CONTRIBUTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/ubcent/react-circular-color/issues)

### Issue Description

[INSERT DESCRIPTION HERE]

### Environment

[INSERT DESCRIPTION HERE]

**Comment by ubcent** [comment]
Sure, I would appreciate that

**Comment by walosha** [comment]
I have raise a PR #18 for review

**Comment by walosha** [comment]
this was not published
