### ISSUE TITLE
Click (touch) handling

### ISSUE THREAD

**Issue by ubcent** [ubcent/react-circular-color#5]
### New Issue Checklist

- [x] Updated package to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/ubcent/react-circular-color/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/ubcent/react-circular-color/issues)

### Issue Description

We need to handle the click (touch) event to get the ability to choose a necessary color directly.

**Comment by codelyne** [comment]
Please, see the pull request https://github.com/ubcent/react-circular-color/pull/7

**Comment by ubcent** [comment]
Closed by #7
