### ISSUE TITLE
Wrong color

### ISSUE THREAD

**Issue by codelyne** [ubcent/react-circular-color#8]
### New Issue Checklist

- [x] Updated package to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/ubcent/react-circular-color/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/ubcent/react-circular-color/issues)

### Steps to reproduce

1. clone the repository
2. execute the commands `npm i` then `npm start`
3. open the browser and go to the [localhost](http://localhost:8080)
4. move the handler to any top-half position on the color circle
5. see the resulting color - it is wrong: actually the color as well as the hex code.
6. note, that the resulting color mirrored from a bottom-half position on the color circle

### Environment

- application: version 1.1.2
- browser: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by ubcent** [comment]
@codelyne thx for reporting, I'll try to figure out what the problem is asap. Or don't you mind to make a pull request?

**Comment by codelyne** [comment]
@ubcent I'll try to solve this issue.

**Comment by ubcent** [comment]
@codelyne deal
